### ISSUE TITLE
BottomSheet not fully hidden

### ISSUE THREAD

**Issue by ndriqimh** [skydoves/FlexibleBottomSheet#10]
- Library Version [0.1.1]
- Affected Device(s) [Samsung Galaxy a13 with Android 13.0]
 
Bottom Sheet is slightly visible at the bottom when it's hidden. You can see the **WHITE** line at the end of the photo

```kotlin
FlexibleBottomSheet(
        sheetState = sheetState,
        windowInsets = WindowInsets.waterfall,
        tonalElevation = 0.dp,
        shape = RectangleShape,
        onDismissRequest = {
            //NOOP
        },
        containerColor = White,
)
``` 
    
```kotlin
FlexibleSheetState(
                flexibleSheetSize = FlexibleSheetSize(fullyExpanded = fullyExpandedRatio),
                isModal = false,
                skipSlightlyExpanded = true,
                skipIntermediatelyExpanded = true,
                containSystemBars = true,
                allowNestedScroll = true,
                animateSpec = SwipeableV2Defaults.AnimationSpec,
)
``` 

![FlexibleBottomSheet](https://github.com/skydoves/FlexibleBottomSheet/assets/44320283/17f80607-6a88-40e8-97d3-4ff1e0539af0)

**Comment by skydoves** [comment]
Hi @ndriqimh, which device do you use?

**Comment by skydoves** [comment]
I'm wondering if it only happens when you close the sheet using the `hide()` method.

**Comment by ndriqimh** [comment]
It was happening also during closing with swipe. I made a quick fix using this code below, this fixes when closing with swipe, but not when closing using `hide()`, probably because the callback `onDismissRequest` isn't being called
```kotlin
    // Using this alpha because sheet doesn't fully hides
    // Should be fixed in new versions
    var alpha by remember { mutableFloatStateOf(1f) }

    FlexibleBottomSheet(
        modifier = Modifier.alpha(alpha),
        sheetState = sheetState,
        windowInsets = WindowInsets.waterfall,
        tonalElevation = 0.dp,
        shape = RectangleShape,
        onDismissRequest = {
            alpha = 0f
        },
        onTargetChanges = {
            alpha = 1f
        },
        containerColor = Color.White,
    )
```

**Comment by skydoves** [comment]
Hey @ndriqimh, I appreciate your detailed description! I just fixed this issue, and it was published on the `0.1.2-SNAPSHOT`. Would you please check it out to see if it works as well as you expected before releasing the stable? Thank you!

**Comment by ndriqimh** [comment]
Hey @skydoves, It seems this versions isn't pushed in maven, I get this
`Failed to resolve: com.github.skydoves:flexible-bottomsheet-material3:0.1.2-SNAPSHOT`
In the meantime if you can check another issue. As per shared code before, I'm just using fullyExtended per this case of mine
```kotlin
flexibleSheetSize = FlexibleSheetSize(
                    fullyExpanded = fullyExpandedRatio,
                    intermediatelyExpanded = 0f,
                    slightlyExpanded = 0f,
                ),
``` 
When I use a scrollable composable like a LazyColumn or a vertically scrollable Column, with allowNestedScroll = true, I can drag/fling the bottom sheet to dismiss but it doesn't hide it. Let's say I'm dragging/flinging it down, when I release the finger the sheet goes right back up to fullyExpanded size again.

**Comment by skydoves** [comment]
Hey @ndriqimh, [0.1.2-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/github/skydoves/flexible-bottomsheet-material-android/0.1.2-SNAPSHOT/) already has been published. 

You need to add the maven download link to your gradle settings.

```gradle
repositories {
   maven(url = "https://oss.sonatype.org/content/repositories/snapshots/")
}
```

**Comment by ndriqimh** [comment]
Hey @skydoves looks good with this, thank you! Let me know if you have anything on the other issue I mentioned.

**Comment by skydoves** [comment]
Hey @ndriqimh, would you create another issue with any screenshots on that? Thank you!

**Comment by skydoves** [comment]
This issue will be delivered in the next stable release. Thanks for helping on this issue!
