### ISSUE TITLE
[NestedScroll] BottomSheet doesn't hide/dismiss when dragging/flinging via the nested scroll area

### ISSUE THREAD

**Issue by ndriqimh** [skydoves/FlexibleBottomSheet#14]
- Library Version [0.1.1]
- Affected Device(s) [Samsung Galaxy A13 with Android 13.0]
 
I have made the bottom sheet to just fully expand for my needed case.
```kotlin
flexibleSheetSize = FlexibleSheetSize(
                    fullyExpanded = fullyExpandedRatio,
                    intermediatelyExpanded = 0f,
                    slightlyExpanded = 0f,
 ),
 FlexibleSheetState(
                flexibleSheetSize = flexibleSheetSize,
                isModal = false,
                skipSlightlyExpanded = true,
                skipIntermediatelyExpanded = true,
                containSystemBars = true,
                allowNestedScroll = true,
                animateSpec = SwipeableV2Defaults.AnimationSpec,
)
``` 
When I use a scrollable composable like a LazyColumn or a vertically scrollable Column, with `allowNestedScroll = true`, I can drag/fling the bottom sheet down to try dismiss it but it doesn't hide it. I more exact words, let's say I'm dragging/flinging it down, when I release the finger the sheet goes right back up to fullyExpanded automatically. I don't have this problem when I don't use a scrollable component. I can't share any images/videos due to the project I'm working on.

**Comment by ndriqimh** [comment]
@skydoves any news on this? Did you had time to check it out?

**Comment by skydoves** [comment]
Duplicated with #15
