### ISSUE TITLE
Make bottom sheet fullscreen (without Android status bar)

### ISSUE THREAD

**Issue by sme3005** [skydoves/FlexibleBottomSheet#19]
In my app I want the status bar from Android at the top of the screen (where time and battery status are shown) to not be visible.
Unfortunately, I didn't find a working solution to expand to the status bar area in the FullyExpanded sheet state.
Instead, on top of the bottom sheet there is some space (where normally the top bar is placed) and there is no way to close the space and make the bottom sheet to fully expand to the top of the screen.

I already tried:
- setting containSystemBars in FlexibleSheetState
- setting WindowInsets in FlexibleBottomSheet (top = 0.dp)

**Comment by skydoves** [comment]
Hi @sme3005 , sorry for the delayed response. You can check out the [sample1 code](https://github.com/skydoves/FlexibleBottomSheet/blob/main/app/src/main/kotlin/com/skydoves/flexiblebottomsheetdemo/FlexibleBottomSheetSample1.kt) for dimming the status bar while you're displaying the bottom sheet like the given screenshot below:

![Screenshot 2024-06-06 at 2 45 20 PM](https://github.com/skydoves/FlexibleBottomSheet/assets/24237865/810af3a2-ad27-4636-b8dd-b622961f7bb0)

If you are still facing the same issue after referring to the code, please re-open it. Thanks!
