### ISSUE TITLE
Scrim doesn't contain statusbar

### ISSUE THREAD

**Issue by chandroidx** [skydoves/FlexibleBottomSheet#2]
**Please complete the following information:**
- Library Version 0.1.0
- Affected Device(s) Samsung Galaxy s23 with Android 13]
 
**Describe the Bug:**
With only Horizontal sides' insets scrim doesn't contain status bar 🧐
``` kotlin
windowInsets = BottomSheetDefaults.windowInsets.only(WindowInsetsSides.Horizontal)
```
<img src="https://github.com/skydoves/FlexibleBottomSheet/assets/58277725/6f9ad0bd-405f-4584-965c-161d960e93d6" width="30%"/>

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hey @chandroidx, sorry for the late response. This is a very expected result since it should be done by the user side.

You can simply resolve this issue by changing the statusbar color like the method below:

1. Add the accompanist dependency below:
```

```kotlin

```

**Comment by skydoves** [comment]
Hey @chandroidx, my apologies for the delayed response. It's expected that this task falls under the responsibility of the user.

To address this issue, you can easily change the status bar color using the following method:

1. Add the accompanist dependency below:
```
implementation("com.google.accompanist:accompanist-systemuicontroller:0.32.0")
```

2. Observe the flexible bottom sheet's target value changes and change the statusbar color when the state value is not hidden like the example below:

```kotlin
  var currentSheetTarget by remember { mutableStateOf(FlexibleSheetValue.IntermediatelyExpanded) }
  val systemUiController = rememberSystemUiController()

  val primaryColor = MaterialTheme.colors.primary
  val scrimColor = Color.Black.copy(alpha = 0.65f)

  LaunchedEffect(currentSheetTarget) {
    if (currentSheetTarget == FlexibleSheetValue.Hidden) {
      systemUiController.setStatusBarColor(
        color = primaryColor
      )
    } else {
      systemUiController.setStatusBarColor(
        color = scrimColor
      )
    }
  }

  FlexibleBottomSheet(
    onDismissRequest = onDismissRequest,
    sheetState = rememberFlexibleBottomSheetState(
      flexibleSheetSize = FlexibleSheetSize(),
      isModal = true,
      skipSlightlyExpanded = false,
    ),
    onTargetChanges = { sheetValue ->
      currentSheetTarget = sheetValue
    },
    containerColor = Color.Black,
    scrimColor = scrimColor
  ) {
     ..
    }
```

This is the result as you've expected:

![Screenshot 2023-12-17 at 2 50 43 PM](https://github.com/skydoves/FlexibleBottomSheet/assets/24237865/ec64f3c3-0023-4148-adcc-ab8cdbf28a11)

**Comment by skydoves** [comment]
Hey @chandroidx, I'm closing this issue for now. If you still face the same problem while addressing it with my suggestion, please reopen and discuss this anytime!
