### ISSUE TITLE
StatusBar dim is not Showing  

### ISSUE THREAD

**Issue by easyhooon** [skydoves/FlexibleBottomSheet#28]
- Library Version 
  -v0.1.2
- Affected Device(s) 
  - Samsung Galaxy zflip4 with Android 14.0 Pixel5(emulator)
 
**Describe the Bug:**
In the case of M3 ModalBottomSheet, Dim processing is possible in the Status Bar area when BottomSheet is on the screen by specifying `windowInsets = WindowInsets(top = 0)`.
But FlexibleBottomSheet not working by by specifying `windowInsets = WindowInsets(top = 0)`.

Add a clear description about the problem.
|M3 ModalBottomSheet|FlexibleBottomSheet|
|:-----:|:-----:|
|<img width="360" src="https://github.com/skydoves/FlexibleBottomSheet/assets/51016231/270f107e-494d-45b7-967a-a9539a468785">|<img width="360" src="https://github.com/skydoves/FlexibleBottomSheet/assets/51016231/9e22e2c5-1aef-4618-ad95-ebb91a9d825d">|

full code is here.
https://github.com/Project-Unifest/unifest-android/blob/develop/core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt

**Expected Behavior:**
I hope dim processing is applied to the Status Bar area.

**Comment by skydoves** [comment]
Hi @easyhooon, sorry for the delayed response. You can check out the [sample1 code](https://github.com/skydoves/FlexibleBottomSheet/blob/main/app/src/main/kotlin/com/skydoves/flexiblebottomsheetdemo/FlexibleBottomSheetSample1.kt) for dimming the status bar while you're displaying the bottom sheet like the given screenshot below:

![Screenshot 2024-06-06 at 2 45 20 PM](https://github.com/skydoves/FlexibleBottomSheet/assets/24237865/810af3a2-ad27-4636-b8dd-b622961f7bb0)

If you are still facing the same issue after referring to the code, please re-open it. Thanks!
