### ISSUE TITLE
Maintain the standard bottom sheet after configuration changes such as device rotation.

### ISSUE THREAD

**Issue by yijia-wang-sap** [skydoves/FlexibleBottomSheet#29]
**Is your feature request related to a problem?**

The standard bottom sheet will be gone after device configuration changes, such as rotating from portrait to landscape mode. 

**Describe the solution you'd like:**

The non-modal standard bottom sheet should remain its state before the configuration changes.

**Comment by skydoves** [comment]
Hey @yijia-wang-sap, you can handle the configuration changes using `rememberSaveable` or something. As FlexibleBottomSheet targets KMP, I don't have any plans yet for supporting the Android configuration changes yet.
