### ISSUE TITLE
Bottom Sheet visibility bug when dismissing

### ISSUE THREAD

**Issue by nilufer32** [skydoves/FlexibleBottomSheet#30]
**Please complete the following information:**
- Library Version [e.g. v1.0.0] : latest commit 1c0e68f041df83fad2a2a957ebb00f0d90ae6762
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 OppoCPH1803 , Samsung A510F, Iphone
**Describe the Bug:**

Add a clear description about the problem.
When dismissing the sheet using a drag gesture, the bottom sheet disappears for a split second then just before completely hiding it reappears again and hides fully. Also, in this state of the sheet "disappearing" if I drag the sheet up instead of down it reappears again.
**Expected Behavior:**

A clear description of what you expected to happen.

The sheet should always be visible on screen as long as I'm dragging it and it should only fully disappear when I fully drag it downwards.

**Comment by H4kt** [comment]
+1

**Comment by skydoves** [comment]
Hey guys, would you provide a video for this behavior? Thank you!

**Comment by Kev1000000** [comment]
This happens when you swipe to dismiss (while still holding your finger down) for me at least.

**Comment by sevbanBayir** [comment]
+1

This exactly happens when you try to swipe to dismiss from anywhere else then `DragHandle

**Comment by skydoves** [comment]
Hey everyone, thanks for checking out this issue. I just confirmed that it occurs when using `LazyColumn` or any scrollable component inside the flexible bottom sheet. Fixing this bug is a high priority for me.

**Comment by skydoves** [comment]
Hey guys, 0.1.4 has been released, and I hope this new release resolves this issue.

**Comment by Kev1000000** [comment]
Hey there, this unfortunately didn't solve the issue for me.  On _some_ scrolls it is fixed, but it still happens about 80% of the time =(

**Comment by skydoves** [comment]
Hey @Kev1000000, do you have any screenshots? and I'm wondering if it happens on dragging or snapping (flinging) behavior?

**Comment by Kev1000000** [comment]
[Screen_recording_20240805_002126.webm](https://github.com/user-attachments/assets/ee8ed0d6-7d35-4309-a21d-1b96ee370ec9)

**Comment by sevbanBayir** [comment]
Same here, issue still persists with 0.1.4 . Im using a Column with a verticalScroll() modifier in FlexibleBottomSheet.

**Comment by TemMax** [comment]
I've noticed that it happens only for non-modal sheets like `rememberFlexibleBottomSheetState(isModal = false)`

**Comment by TemMax** [comment]
UPD: nope, it happens for modal sheets as well. But when the sheet is modal, there is no padding glitch, only disappearing happens.

**Comment by skydoves** [comment]
Hi everyone, the new release 0.1.5 has been released, and it fixes for the modal case.
