### ISSUE TITLE
In a non-Compose project, what libraries are good options to achieve an effect similar to FlexibleBottomSheet and offer equally convenient functionality?

### ISSUE THREAD

**Issue by yiyeshua** [skydoves/FlexibleBottomSheet#35]
My project is a mixed one using both Kotlin and Java, and it doesn't utilize Compose. Apart from the official BottomSheet, are there any similar libraries available?

**Comment by skydoves** [comment]
Aren't there many ways to implement this in XML, such as using `BottomSheetDialogFragment`?
