### ISSUE TITLE
Question about the usage of internal APIs in the bottom sheet implementation

### ISSUE THREAD

**Issue by StylianosGakis** [skydoves/FlexibleBottomSheet#36]
This is not a feature request nor a bug report, I was mostly curious about the lines I can see inside here in particular https://github.com/skydoves/FlexibleBottomSheet/blob/688b8f716c3828a5eb1871f5c14ddba7d96f9037/flexible-core/src/androidMain/kotlin/com/skydoves/flexible/core/FlexibleBottomSheetPopup.kt#L182-L191

I am only asking because I am concerned about what kind of risks you think one would be opting into while using this. And what are the chances that these private APIs will change in the future in a backwards incompatible way making this not work as expected in future Android API levels. If that were to happen, can the library update the code accordingly to keep all of this working as expected?

**Comment by skydoves** [comment]
Hey @StylianosGakis, sorry for the late response. That's an interesting question. Yes, the FlexibleBottomSheet uses reflection to access private fields in `WindowManager`. However, you don't need to worry about it, as the code in `WindowManager` has remained unchanged for 13 years 😄, as you can see in the AOSP: 
https://android.googlesource.com/platform/frameworks/base/+log/539ee87/core/java/android/view/WindowManager.java
