### ISSUE TITLE
can i set isModal?

### ISSUE THREAD

**Issue by kiminowhite** [skydoves/FlexibleBottomSheet#38]
I want to modify the current value of isModal based on the folded state. It seems that this value can only be set when creating a sheetState for the first time. When user interaction is allowed behind the folded page, the current shadow effect will be cancelled. I hope to only allow user operation during the first layer of folding, and maintain shadows and not allow user operation during the subsequent two folds. Can this be achieved. (I am a beginner and this is a mechanical translation. I hope you can understand what I mean.)

**Comment by skydoves** [comment]
Hey @kiminowhite, for now, unfortunately, you can't change the property of the `isModal`  after completely creating the flexible bottom sheet since the internal measurement system. I will let you know if there's any solution later. Thank you!
