### ISSUE TITLE
Is it possible to customize the Drag Handle?

### ISSUE THREAD

**Issue by trietbui85** [skydoves/FlexibleBottomSheet#46]
**Is your feature request related to a problem?**
I want to customize the Drag Handle View. Is it possible?
For example: if expand is less than Intermediately, will be the Arrow Up icon. Otherwise, would be Arrow Down icon.

<img width="264" alt="image" src="https://github.com/user-attachments/assets/c550f6a1-dc34-4867-a1b5-64a4389778d8">

**Comment by daniel-dawson** [comment]
@trietbui85 there's a `dragHandle` parameter. Does that not fit your use case?

**Comment by trietbui85** [comment]
Ah, yes it is.
