### ISSUE TITLE
Adding support for "enableEdgeToEdge()"

### ISSUE THREAD

**Issue by kjsolo** [skydoves/FlexibleBottomSheet#52]
https://developer.android.com/develop/ui/compose/layouts/insets

**Comment by skydoves** [comment]
Hey @kjsolo would you re-open this issue with the details? If I'm correct, this library works well with the "enableEdgeToEdge" function.

**Comment by BackPackerDz** [comment]
https://github.com/user-attachments/assets/eb8b5cc8-6f61-4bd0-a2d1-6ed94e682904

I'm having an issue with `enableEdgeToEdge()` as you can see in the video, it has a weird behavior @skydoves @kjsolo
