### ISSUE TITLE
When isModal is true screen turns white instead of dimmed

### ISSUE THREAD

**Issue by carvalho2707** [skydoves/FlexibleBottomSheet#58]
**Please complete the following information:**
- Library Version 0.1.5
- Affected Device(s) All
 
**Describe the Bug:**
When I set my BottomSheet to isModal = true the screen content( Except the bottom sheet) turns white instead of just dimmed.
This issue doesn't happen with isModal=false 

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.
When a modal is created the rest of the screen should change the color to be slightly dimmed to focus the attention on the bottom sheet instead

**Comment by carvalho2707** [comment]
![Screenshot_20240906_094339](https://github.com/user-attachments/assets/b0fde942-cf34-4fcd-afd9-6e45572bd0a4)

**Comment by skydoves** [comment]
Have you ever adjusted the scrim color of your material theme? Hence the flexible bottomsheet uses the scrim color of the material them below:

```kotlin
MaterialTheme.colorScheme.scrim.copy(alpha = 0.32f)
```
